import {
  AlertCircle,
  AlertTriangle,
  BadgeCheck,
  Ban,
  CalendarCheck,
  Check,
  CheckCircle2,
  CircleDashed,
  Clock,
  Euro,
  Hourglass,
  IdCard,
  Inbox,
  KeyRound,
  Landmark,
  Mail,
  Pause,
  Pencil,
  Send,
  ShieldCheck,
  FileSignature,
  Wrench,
  XCircle,
  type LucideIcon,
} from "lucide-react";
import type { StatusIconName } from "@/lib/status-dictionary";

/** The icon of each state. Every state has one: its meaning is never only a color. */
export const STATUS_ICONS: Record<StatusIconName, LucideIcon> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "badge-check": BadgeCheck,
  ban: Ban,
  "calendar-check": CalendarCheck,
  check: Check,
  "check-circle": CheckCircle2,
  "circle-dashed": CircleDashed,
  clock: Clock,
  euro: Euro,
  hourglass: Hourglass,
  "id-card": IdCard,
  inbox: Inbox,
  key: KeyRound,
  landmark: Landmark,
  mail: Mail,
  pause: Pause,
  pencil: Pencil,
  send: Send,
  "shield-check": ShieldCheck,
  signature: FileSignature,
  wrench: Wrench,
  "x-circle": XCircle,
};
