import { useTranslation } from 'react-i18next';
import { AI_CONTENT_NOTICE_KEYS, type AiContentKind } from './ai-content-notice-keys';

interface AiContentNoticeProps {
  /** Show the notice. Mount it next to AI-generated content only, with the flag the API gives (never a constant). */
  visible?: boolean;
  kind?: AiContentKind;
}

/** EU AI Act transparency note for content generated by AI (US-003 AC9, SE-05). Nothing is rendered unless `visible`. */
export function AiContentNotice({ visible = false, kind = 'generic' }: AiContentNoticeProps) {
  const { t } = useTranslation();

  if (!visible) return null;

  return (
    <p className="text-xs text-muted-foreground italic" data-testid="ai-content-notice" data-kind={kind}>
      {t(AI_CONTENT_NOTICE_KEYS[kind])}
    </p>
  );
}
