import { useTranslation } from 'react-i18next';

/**
 * What the AI-generated content is, to word the notice: `generic` (a text written by AI), `seo` (a public guide that an
 * admin approved), `draft` (a draft waiting for the admin's review), `supplierReason` (why a supplier is recommended).
 */
export type AiContentKind = 'generic' | 'seo' | 'draft' | 'supplierReason';

/** Translation keys of the notices (`aiContentNotice.*`), one per kind. */
export const AI_CONTENT_NOTICE_KEYS: Record<AiContentKind, string> = {
  generic: 'aiContentNotice.label',
  seo: 'aiContentNotice.seo',
  draft: 'aiContentNotice.draft',
  supplierReason: 'aiContentNotice.supplierReason',
};

interface AiContentNoticeProps {
  /** Show the notice. Mount it next to AI-generated content only, with the flag the API gives (never a constant). */
  visible?: boolean;
  kind?: AiContentKind;
}

/** EU AI Act transparency note for content generated by AI (US-003 AC9, SE-05). Nothing is rendered unless `visible`. */
export function AiContentNotice({ visible = false, kind = 'generic' }: AiContentNoticeProps) {
  const { t } = useTranslation();

  if (!visible) return null;

  return (
    <p className="text-xs text-muted-foreground italic" data-testid="ai-content-notice" data-kind={kind}>
      {t(AI_CONTENT_NOTICE_KEYS[kind])}
    </p>
  );
}
