/**
 * `robots.txt` of the web app (SE-02, A8-02), generated by `vite build` into `dist/robots.txt`. Pure module without
 * Vite or DOM types: `vite.config.ts` runs it at build time.
 *
 * - Vercel production (`VERCEL_ENV=production`): indexing allowed and the sitemap declared on the public domain
 *   `VITE_PUBLIC_SITE_URL` (the same domain as the backend `App__PublicSiteBaseUrl`). No default domain (decision D3):
 *   a missing or invalid value fails the build, so Vercel keeps the previous deployment.
 * - Everywhere else (Vercel preview and the `develop` test deployment, local and CI builds): `Disallow: /`, so a test
 *   environment is never indexed.
 *
 * Runbook: backend `docs/runbooks/seo-domain.md`.
 */

/** Path of the sitemap on the web app domain (served by the Vercel function `api/sitemap.ts`). */
export const SITEMAP_PATH = '/sitemap.xml';

export interface RobotsTxtInput {
  /** Value of `VERCEL_ENV` on Vercel (`production`, `preview`, `development`), undefined elsewhere. */
  vercelEnv: string | undefined;
  /** Value of `VITE_PUBLIC_SITE_URL` seen by Vite (process environment or `.env` files). */
  publicSiteUrl: string | undefined;
}

/** Origin of the public site (`https://host[:port]`), or an error message when the value cannot be one. */
export function parsePublicSiteUrl(value: string | undefined): { origin: string } | { error: string } {
  const trimmed = value?.trim();
  if (!trimmed) {
    return { error: 'VITE_PUBLIC_SITE_URL is missing: set the public URL of the web app (https://<domain>).' };
  }

  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    return { error: `VITE_PUBLIC_SITE_URL "${trimmed}" is not an absolute URL: use https://<domain>.` };
  }

  if (url.protocol !== 'https:') {
    return { error: `VITE_PUBLIC_SITE_URL "${trimmed}" must use https.` };
  }
  if ((url.pathname !== '/' && url.pathname !== '') || url.search || url.hash || url.username || url.password) {
    return {
      error: `VITE_PUBLIC_SITE_URL "${trimmed}" must be the site root (scheme and host only): the SPA is served at /.`,
    };
  }

  return { origin: url.origin };
}

/** Content of `robots.txt` for a build; throws on a production build without a valid public URL. */
export function buildRobotsTxt({ vercelEnv, publicSiteUrl }: RobotsTxtInput): string {
  if (vercelEnv !== 'production') {
    return ['# Not a production deployment: nothing here may be indexed.', 'User-agent: *', 'Disallow: /', ''].join(
      '\n',
    );
  }

  const parsed = parsePublicSiteUrl(publicSiteUrl);
  if ('error' in parsed) {
    throw new Error(
      `${parsed.error} It is required on the Vercel Production environment (robots.txt declares the sitemap on it).`,
    );
  }

  return ['User-agent: *', 'Allow: /', '', `Sitemap: ${parsed.origin}${SITEMAP_PATH}`, ''].join('\n');
}
